name: how-to-hyperopt
channels:
  - defaults
dependencies:
  - pip=21.0.1
  - python=3.8.8
  - pip:
    - keras==2.7.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - keras-tuner==1.0.4
    - markdown==3.3.4
    - numpy==1.19.5
    - pandas==1.3.4
    - gensim==4.0.0
    - scikit-learn==1.3.0
    - sktime==0.21.0
    - matplotlib==3.4.3
    - protobuf==3.20.0
    - tensorboard==2.7.0
    - tensorflow==2.13.0
    - nltk==3.6.7
    - regex==2023.6.3
prefix:
